### ISSUE TITLE
Start giftless-client-js with batch method implemented

### ISSUE THREAD

**Issue by cotts** [datopian/giftless-client-js#1]
I want a JS client for Giftless server like python one https://github.com/datopian/giftless-client that provides convenience methods e.g.

```javascript=
class Client
  // same as python ...
  init(lfs_server, token, ...)
  
  // low level api
  batch(prefix, operation, objects, ref=None, transfers=None)
```

See for reference python implementation https://github.com/datopian/giftless-client. Note we don't need all the methods: the main one would be the getUrl function.

Should work in node and browser (can prioritize node for now).

## Acceptance

* [x] Stubbed repo with README and MIT license
* [x] class object `Client` **DONE**: https://github.com/datopian/giftless-client-js/blob/main/src/client.js
* [x] `batch` function **DONE**: https://github.com/datopian/giftless-client-js/blob/main/src/client.js
* [x ] Create package.json and published to npm as e.g. `giftless-client` **DONE**: https://www.npmjs.com/package/giftless-client

## Tasks

* [x] Stub repo with README and MIT license
* [x] Create test for client instantiation **DONE**: https://github.com/datopian/giftless-client-js/blob/main/__tests__/test_client.js
* [x] Have `Client` object and have tests passing **DONE**: https://github.com/datopian/giftless-client-js/blob/main/src/client.js
* [x] Add github action to run tests automatically **DONE**: https://github.com/datopian/giftless-client-js/blob/main/.github/workflows/main.yml
* [x] Have test for batch method (mock out call to giftless server) **DONE**: https://github.com/datopian/giftless-client-js/blob/main/__tests__/test_client.js
* [x] Implement batch method **DONE**: https://github.com/datopian/giftless-client-js/blob/main/src/client.js
* [x] Add package.json and publish to npm with datopian as an owner **DONE**: https://www.npmjs.com/package/giftless-client

**Comment by rufuspollock** [comment]
@steveoni can we close this please ...
