### ISSUE TITLE
`upload` method for uploading files to storage

### ISSUE THREAD

**Issue by rufuspollock** [datopian/giftless-client-js#6]
You can copy over from https://github.com/datopian/ckan-client-js/blob/706247c99ec1a40e855f8612ef466c305f3f585e/lib/lfs-client.js#L4

Tests would be adapted (to be for giftless client) from https://github.com/datopian/ckan-client-js/blob/master/test/upload.test.js

## Acceptance

* [x] Upload works: **DONE**-  https://github.com/datopian/giftless-client-js/blob/feature/upload/src/index.js
* [x] There is a test with mocks: **DONE**- https://github.com/datopian/giftless-client-js/blob/feature/upload/__tests__/test_upload.js

## Tasks

* [x] Move code for LfsClient.GitLfsClient from [ckan-client-js](https://github.com/datopian/ckan-client-js/) to [giftless-client-js](https://github.com/datopian/giftless-client-js/) **DONE** - https://github.com/datopian/giftless-client-js/blob/feature/upload/src/index.js  AND https://github.com/datopian/giftless-client-js/blob/feature/upload/src/transfer.js
  * [x] Steven: good check is to compare your batch code to code there to see how close it is 😉 **DONE**
  * [x] Open an issue in ckan-client-js to refactor to use that code and remove it from ckan-client-js (we can do that later) – **DONE: Issue opened here https://github.com/datopian/ckan-client-js/issues/41**
  * [x] Add documentation on usage to README **DONE** - https://github.com/datopian/giftless-client-js/blob/feature/upload/README.md
